### ISSUE TITLE
 How do I use it?

### ISSUE THREAD

**Issue by w4567892015** [hbrok/markdown-preview-bitbucket#1]
How do I use it ?
I use visual studio code, please help me thanks

**Comment by hbrok** [comment]
Check out the [Visual Studio Code markdown preview documentation](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview), it has instructions on how to open a markdown preview. You'll see the BitBucket styles in the preview.

**Comment by w4567892015** [comment]
alright, I use this extensions "Markdown Preview Enhanced" , but it not use your style, so i will search how to change it, did you have some idea you can tell me. thanks

**Comment by hbrok** [comment]
It seems like Markdown Preview Enhanced uses its own markdown rendering engine which is why the styles don't show up with it.

If you want to have the BitBucket styles you could try copying the CSS from [bitbucket-markdown.css](https://github.com/hbrok/markdown-preview-bitbucket/blob/master/bitbucket-markdown.css) and [base.css](https://github.com/hbrok/markdown-preview-bitbucket/blob/master/base.css) and using the MPE [customize CSS feature](https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css) to add them to Markdown Preview Enhanced.

**Comment by w4567892015** [comment]
okay, I have tried to copy bitbucket-markdown.css file to style. It's useful. thanks

**Comment by hbrok** [comment]
Great! I'm glad it worked for you.
